version: "3.9"
services:
    db:
        container_name: db
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            MSSQL_SA_PASSWORD: "!suPerSecret5Assword!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
    web:
        container_name: web
        environment:
            DbServer: db
            DbUser: sa
            DbPassword: "!suPerSecret5Assword!"
            IdentityDatabase: TestMusicDroneIdentityDb
        build: .
        ports:
            - "8080:5000"
        depends_on:
            - db
