on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TESTING_ENVIRONMENT: CI
    steps:
      - name: Check out code
        uses: actions/checkout@v2.1.0
      - name: Start dependencies (docker-compose)
        run: |
                    docker-compose up -d  
      - name: Wait for SQL Server container
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Add xunit.runner.console
        run: dotnet add package xunit.runner.console --version 2.4.1
      - name: Test
        run: dotnet test --no-build -v n